###############################################################################
#
###############################################################################
PYTHON_VER=python3.6
GMAKE=make-4.3
GTAR=tar-1.32
GMP=gmp-6.1.0
MPFR=mpfr-3.1.4
MPC=mpc-1.0.3
ISL=isl-0.18
KERNEL=linux-4.19.13
BINUTILS=binutils-2.34
GCC=gcc-10.2.0
GLIBC=glibc-2.30
NEWLIB=newlib-3.1.0
GDB=gdb-9.2
QEMU=qemu-5.0.0
EDK2=edk2-current
SWIG=swig-4.0.2
CMAKE=cmake-3.18.1
Z3=z3-4.8.8
LLVM_REL_TAG=llvmorg-10.0.1
EDK2_GIT_REPO="git@github.com:tianocore/edk2.git"
NINJA_GIT_REPO="https://github.com/martine/ninja.git"
LLVM_GIT_REPO="https://github.com/llvm/llvm-project.git"
DOWNLOAD_URLS="ftp://ftp.gnu.org/gnu/make/make-4.3.tar.gz
ftp://ftp.gnu.org/gnu/tar/tar-1.32.tar.gz
ftp://gcc.gnu.org/pub/gcc/infrastructure/gmp-6.1.0.tar.bz2
ftp://gcc.gnu.org/pub/gcc/infrastructure/mpfr-3.1.4.tar.bz2
ftp://gcc.gnu.org/pub/gcc/infrastructure/mpc-1.0.3.tar.gz
ftp://gcc.gnu.org/pub/gcc/infrastructure/isl-0.18.tar.bz2
https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.19.13.tar.gz
https://ftp.gnu.org/gnu/binutils/binutils-2.34.tar.gz
https://ftp.gnu.org/gnu/gcc/gcc-10.2.0/gcc-10.2.0.tar.gz
https://ftp.gnu.org/gnu/libc/glibc-2.30.tar.gz
https://ftp.gnu.org/gnu/gdb/gdb-9.2.tar.gz
https://download.qemu.org/qemu-5.0.0.tar.xz
ftp://sourceware.org/pub/newlib/newlib-3.1.0.tar.gz
https://github.com/Kitware/CMake/releases/download/v3.18.1/cmake-3.18.1.tar.gz
https://github.com/Z3Prover/z3/archive/z3-4.8.8.tar.gz
https://opensource.apple.com/source/lldb/lldb-69/utils/emacs/gud.el
http://prdownloads.sourceforge.net/swig/swig-4.0.2.tar.gz"
