###############################################################################
#
###############################################################################
NO_ELF_TARGETS="sparc64"
NO_LINUX_TARGETS=""
PYTHON_VER=python3.6
GMAKE=make-4.3
GTAR=tar-1.34
GMP=gmp-6.1.0
MPFR=mpfr-3.1.4
MPC=mpc-1.0.3
ISL=isl-0.18
KERNEL=linux-5.14.7
BINUTILS=binutils-2.37
GCC=gcc-11.2.0
GLIBC=glibc-2.34
NEWLIB=newlib-4.1.0
GDB=gdb-11.1
QEMU=qemu-6.1.0
EDK2=edk2-current
SWIG=swig-4.0.2
CMAKE=cmake-3.21.3
Z3=z3-4.8.12
LLVM_REL_TAG="llvmorg-12.0.1"
EDK2_GIT_REPO="git@github.com:tianocore/edk2.git"
NINJA_GIT_REPO="https://github.com/martine/ninja.git"
LLVM_GIT_REPO="https://github.com/llvm/llvm-project.git"
DOWNLOAD_URLS="https://ftp.gnu.org/gnu/make/make-4.3.tar.gz
https://ftp.gnu.org/gnu/tar/tar-1.34.tar.gz
https://gcc.gnu.org/pub/gcc/infrastructure/gmp-6.1.0.tar.bz2
https://gcc.gnu.org/pub/gcc/infrastructure/mpfr-3.1.4.tar.bz2
https://gcc.gnu.org/pub/gcc/infrastructure/mpc-1.0.3.tar.gz
https://gcc.gnu.org/pub/gcc/infrastructure/isl-0.18.tar.bz2
https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.14.7.tar.gz
https://ftp.gnu.org/gnu/binutils/binutils-2.37.tar.gz
https://ftp.gnu.org/gnu/gcc/gcc-11.2.0/gcc-11.2.0.tar.gz
https://ftp.gnu.org/gnu/libc/glibc-2.34.tar.gz
https://ftp.gnu.org/gnu/gdb/gdb-11.1.tar.gz
https://download.qemu.org/qemu-6.1.0.tar.xz
https://sourceware.org/pub/newlib/newlib-4.1.0.tar.gz
https://github.com/Kitware/CMake/releases/download/v3.21.3/cmake-3.21.3.tar.gz
https://github.com/Z3Prover/z3/archive/z3-4.8.12.tar.gz
https://opensource.apple.com/source/lldb/lldb-69/utils/emacs/gud.el
http://prdownloads.sourceforge.net/swig/swig-4.0.2.tar.gz
https://ftp.gnu.org/gnu/binutils/binutils-2.24.tar.gz
https://ftp.gnu.org/gnu/gcc/gcc-8.4.0/gcc-8.4.0.tar.gz
https://sourceware.org/pub/newlib/newlib-2.5.0.tar.gz
https://ftp.gnu.org/gnu/gdb/gdb-7.12.tar.gz
https://gcc.gnu.org/pub/gcc/infrastructure/isl-0.12.2.tar.bz2
https://llvm-gcc-renesas.com/downloads/d.php?f=v850/binutils/14.01/binutils-2.24_v850_v14.01.tar.bz2
https://llvm-gcc-renesas.com/downloads/d.php?f=v850/newlib/14.01/newlib-2.1.0_v850_v14.01.tar.bz2
https://llvm-gcc-renesas.com/downloads/d.php?f=v850/gcc/14.01/gcc-4.9.2_v850_v14.01.tar.bz2
https://llvm-gcc-renesas.com/downloads/d.php?f=v850/gdb/14.01/gdb-7.8.1_v850_v14.01.tar.bz2
"
